# Generated by Django 4.0.2 on 2022-02-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SK', 'Sakura'), ('RM', 'Romance'), ('JY', 'Juicy'), ('IE', 'Intricate'), ('DY', 'Destiny'), ('HY', 'Honey'), ('PL', 'Pl'), ('FL', 'Floral')], max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('K', 'KP'), ('C', 'Cash')], max_length=1)),
                ('payment_id', models.CharField(default='cash', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.customer')),
                ('items', models.ManyToManyField(related_name='carts', to='invoice.Product')),
            ],
        ),
    ]
