# Generated by Django 4.0.2 on 2022-03-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_product_name'),
        ('invoice', '0005_auto_20220312_1227'),
    ]

    operations = [
    ]
